// embed-zen-key encrypts OPENCODE_ZEN_API_KEY and writes embedded.go.
//
// Usage:
//
//	OPENCODE_ZEN_API_KEY=sk-... go run ./script/embed-zen-key
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	plain := strings.TrimSpace(os.Getenv("OPENCODE_ZEN_API_KEY"))
	if plain == "" {
		fmt.Fprintln(os.Stderr, "embed-zen-key: set OPENCODE_ZEN_API_KEY")
		os.Exit(1)
	}

	key := deriveKey()
	block, err := aes.NewCipher(key)
	if err != nil {
		fatal(err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		fatal(err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		fatal(err)
	}
	cipherText := gcm.Seal(nil, nonce, []byte(plain), nil)

	out := filepath.Join("internal", "cortexconfig", "zenkey", "embedded.go")
	content := fmt.Sprintf(`// Code generated by script/embed-zen-key; DO NOT EDIT.
package zenkey

// Encrypted OpenCode Zen API key (AES-256-GCM). Decrypted at runtime via Key().
var encNonce = [12]byte{%s}

var encCipher = []byte{%s}
`, formatBytes(nonce), formatBytes(cipherText))

	if err := os.WriteFile(out, []byte(content), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("Wrote %s (%d byte ciphertext)\n", out, len(cipherText))
}

func deriveKey() []byte {
	seed := append(append(append([]byte{}, partA...), partB...), partC...)
	seed = append(seed, partD...)
	sum := sha256.Sum256(seed)
	return sum[:]
}

var partA = []byte{
	0x63, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2d, 0x7a,
	0x65, 0x6e, 0x2d, 0x76, 0x31, 0x3a, 0x4d, 0x61,
}

var partB = []byte{
	0x74, 0x65, 0x6f, 0x39, 0x33, 0x3a, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x7a,
}

var partC = []byte{
	0x65, 0x6e, 0x3a, 0x62, 0x75, 0x69, 0x6c, 0x74,
	0x69, 0x6e, 0x3a, 0x6d, 0x69, 0x6d, 0x6f, 0x2d,
}

var partD = []byte{
	0x76, 0x32, 0x2e, 0x35, 0x2d, 0x66, 0x72, 0x65,
	0x65, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}

func formatBytes(b []byte) string {
	if len(b) == 0 {
		return ""
	}
	var sb strings.Builder
	for i, v := range b {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "0x%02x", v)
	}
	return sb.String()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "embed-zen-key:", err)
	os.Exit(1)
}
