#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 <version> --repo <owner/repo> [--dist <path>]"
  echo "  e.g. $0 v0.25.3 --repo Mateooo93/cortex-cli"
  echo ""
  echo "  Updates packaging/winget manifests with version, URLs, and SHA256."
  exit 1
}

VERSION=""
REPO=""
DIST_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      REPO="$2"
      shift 2
      ;;
    --dist)
      DIST_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      if [[ -z "$VERSION" ]]; then
        VERSION="$1"
      else
        echo "Unknown argument: $1"
        usage
      fi
      shift
      ;;
  esac
done

if [[ -z "$VERSION" || -z "$REPO" ]]; then
  usage
fi

if [[ "$VERSION" != v* ]]; then
  VERSION="v$VERSION"
fi
SEMVER="${VERSION#v}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ -z "$DIST_DIR" ]]; then
  DIST_DIR="$ROOT_DIR/dist"
fi

WINGET_DIR="$ROOT_DIR/packaging/winget/Mateooo93.Cortex"
if [[ ! -d "$WINGET_DIR" ]]; then
  echo "!! Missing $WINGET_DIR"
  exit 1
fi

sha_of() {
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "!! Missing $file (run publish.sh first)" >&2
    exit 1
  fi
  shasum -a 256 "$file" | awk '{print $1}'
}

SHA_AMD64=$(sha_of "$DIST_DIR/cortex-windows-amd64.exe")
SHA_ARM64=$(sha_of "$DIST_DIR/cortex-windows-arm64.exe")
RELEASE_URL="https://github.com/${REPO}/releases/download/${VERSION}"

cat > "$WINGET_DIR/Mateooo93.Cortex.installer.yaml" <<YAML
# Generated by script/publish-winget.sh — do not edit version/hash by hand.
PackageIdentifier: Mateooo93.Cortex
PackageVersion: ${SEMVER}
InstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: ${RELEASE_URL}/cortex-windows-amd64.exe
    InstallerSha256: ${SHA_AMD64}
    Commands:
      - cortex
  - Architecture: arm64
    InstallerUrl: ${RELEASE_URL}/cortex-windows-arm64.exe
    InstallerSha256: ${SHA_ARM64}
    Commands:
      - cortex
ManifestType: installer
ManifestVersion: 1.6.0
YAML

cat > "$WINGET_DIR/Mateooo93.Cortex.yaml" <<YAML
# Generated by script/publish-winget.sh
PackageIdentifier: Mateooo93.Cortex
PackageVersion: ${SEMVER}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
YAML

LOCALE="$WINGET_DIR/Mateooo93.Cortex.locale.en-US.yaml"
if [[ -f "$LOCALE" ]]; then
  sed -i "s/^PackageVersion: .*/PackageVersion: ${SEMVER}/" "$LOCALE"
fi

echo "==> Updated winget manifests for $SEMVER"
echo "    windows-amd64: $SHA_AMD64"
echo "    windows-arm64: $SHA_ARM64"